package be.vinci.pae.services;

import java.sql.PreparedStatement;

/**
 * DALServices interface that provide the method to create PreparedStatements.
 */
public interface DalBackendServices {

  /**
   * Return the PreparedStatement associated at the request.
   *
   * @param request           the sql request
   * @param autoGeneratedKeys whether auto generated keys should be returned
   * @return the PreparedStatement of this sql request
   */
  PreparedStatement getPreparedStatement(String request, boolean autoGeneratedKeys);

  /**
   * Return the PreparedStatement associated at the request, without the auto generated keys.
   *
   * @param request the sql request
   * @return the PreparedStatement of this sql request
   */
  PreparedStatement getPreparedStatement(String request);

}
