### Login as user/helper
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "constantine@ressourcerie.be",
  "password": "password"
}

> {%
  client.global.set("helperToken", response.body.token);
%}

### Get all notifications
GET {{baseUrl}}/notifications/user/5
Authorization: {{helperToken}}

### Set notification as read
PATCH {{baseUrl}}/notifications/1/read
Authorization: {{helperToken}}