### Login as user/helper
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "constantine@ressourcerie.be",
  "password": "password"
}

> {%
  client.global.set("helperToken", response.body.token);
%}

### Get all notifications
GET {{baseUrl}}/notifications/user/2
Authorization: {{helperToken}}

### Set notification as read
GET {{baseUrl}}/notifications/4/read
Authorization: {{helperToken}}