### Login as manager
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "riez@ressourcerie.be",
  "password": "password"
}

> {%
  client.global.set("managerToken", response.body.token);
%}

### Login as helper
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "bernard@ressourcerie.be",
  "password": "password"
}

> {%
  client.global.set("helperToken", response.body.token);
%}

### Get a list of all objects
GET {{baseUrl}}/objects
Authorization: {{helperToken}}

### Get a list of all objects offered by a user
GET {{baseUrl}}/objects/user/1
Authorization: {{helperToken}}

### Get a list of all offers
GET {{baseUrl}}/objects/offers
Authorization: {{helperToken}}

### Get an object
GET {{baseUrl}}/objects/1

### Set a object in the workshop
PUT {{baseUrl}}/objects/1
Content-Type: application/json
Authorization: {{helperToken}}

{
  "description": "Garde Robe",
  "type": "Meuble",
  "price": null,
  "state": "en atelier",
  "date": null,
  "isVisible": true
}

### Set a object on sale with a price
PUT {{baseUrl}}/objects/3
Content-Type: application/json
Authorization: {{helperToken}}

{
  "description": "Garde Robe",
  "type": "Meuble",
  "price": 9,
  "state": "mis en vente",
  "date": null,
  "isVisible": true
}

### Try to accept an offer as helper
PATCH {{baseUrl}}/objects/status/2
Content-Type: application/json
Authorization: {{helperToken}}

{
  "status": "accepté"
}

### Accept an offer as manager
PATCH {{baseUrl}}/objects/status/2
Content-Type: application/json
Authorization: {{managerToken}}

{
  "status": "accepté"
}

### Refuse an offer without reason for refusal
PATCH {{baseUrl}}/objects/status/1
Content-Type: application/json
Authorization: {{helperToken}}

{
  "status": "refusé",
  "reasonForRefusal": null
}

### Refuse an offer with an empty reason for refusal
PATCH {{baseUrl}}/objects/status/1
Content-Type: application/json
Authorization: {{managerToken}}

{
  "status": "refusé",
  "reasonForRefusal": ""
}

### Refuse an offer with a reason for refusal
PATCH {{baseUrl}}/objects/status/1
Content-Type: application/json
Authorization: {{helperToken}}

{
  "status": "refusé",
  "reasonForRefusal": "Meuble en trop mauvais état"
}