### Login the default user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email":"tanguy@gmail.com",
  "password":"password"
}

> {%
  client.global.set("tanguyToken", response.body.token);
%}

