### Login as helper
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "riez@ressourcerie.be",
  "password": "password"
}

> {%
  client.global.set("helperToken", response.body.token);
%}

### Login as non helper user
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "lise@ressourcerie.be",
  "password": "password"
}

> {%
  client.global.set("nonHelperToken", response.body.token);
%}

### Login the wrong email user
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "tanguy@ressourcerie.be",
  "password": "password"
}

### Login the wrong mdp user
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "constantine@ressourcerie.be",
  "password": "pwd"
}

### Register new user
POST {{baseUrl}}/users/register
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="lastname"

Ile
--boundary
Content-Disposition: form-data; name="firstname"

Théophile

--boundary
Content-Disposition: form-data; name="phone"

0488 35 33 89

--boundary
Content-Disposition: form-data; name="email"

theo.phile@proximus.be

--boundary
Content-Disposition: form-data; name="password"

mdpuser.3

### Register new user
POST {{baseUrl}}/users/register
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="lastname"

cruise
--boundary
Content-Disposition: form-data; name="firstname"

tom

--boundary
Content-Disposition: form-data; name="phone"

0456454567

--boundary
Content-Disposition: form-data; name="email"

tom@ressourcerie.be

--boundary
Content-Disposition: form-data; name="password"

pwd

### Login non helper
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "tom@ressourcerie.be",
  "password": "pwd"
}


### Get the user
GET {{baseUrl}}/users/my
Content-Type: application/json
Authorization: {{nonHelperToken}}

### Get a list of all users
GET {{baseUrl}}/users
Authorization: {{helperToken}}

### Get a list of all users with query
GET {{baseUrl}}/users?query=riez
Authorization: {{helperToken}}

### Update a user's own info as the user
PATCH {{baseUrl}}/users/4
Authorization: {{nonHelperToken}}
Content-Type: application/json

{
  "firstName": "Bart",
  "currentPassword": "password"
}

### Update a user's role as helper
PATCH {{baseUrl}}/users/4
Authorization: {{helperToken}}
Content-Type: application/json

{
  "role": "aidant"
}